### ISSUE TITLE
CORS error using app-pouchdb-query on remote CouchDB

### ISSUE THREAD

**Issue by garcianavalon** [PolymerElements/app-pouchdb#24]
### Description

After setting up a remote CouchDB and [activating CORS](https://pouchdb.com/guides/setup-couchdb.html#set-up-cors) I still get a `"Referer header must match host."` error when using `app-pouchdb-query`

``` html
<app-pouchdb-query
        db-name="http://localhost:5984/kittens"
        selector="_id $gt null"
        data="{{data}}">
  </app-pouchdb-query>
```
### Expected outcome

The documents in the database are loaded in data
### Actual outcome

``` http
POST http://localhost:5984/kittens/_find 400 (Bad Request)
```

``` javascript
Object {error: "bad_request", reason: "Referer header must match host.", status: 400, name: "bad_request", message: "Referer header must match host."}
```
### Steps to reproduce
1. Install and configure a remote CouchDB running in localhost:5984
2. Put a `app-pouchdb-query` element as defined above in the page.
3. Open the page in a web browser.
4. See the console
### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by bfredo123** [comment]
Hi,

did you get a way to fix this?

It seems to relate to: 
https://github.com/pouchdb/pouchdb/issues/5810
https://github.com/pouchdb/pouchdb/issues/5501

Thanks

**Comment by garcianavalon** [comment]
Yes! 
I changed the CouchDB version from 1.X to 2.Y and worked perfectly :)
I'm using [this unofficial docker](https://hub.docker.com/r/klaemo/couchdb/) image because the official one is not yet at 2 and failed.

Sad news is I couldn't locate the cause of the error for those that can't upgrade :(
