### ISSUE TITLE
Is app-pouchdb-sync functional?

### ISSUE THREAD

**Issue by garcianavalon** [PolymerElements/app-pouchdb#25]
### Description
`app-pouchdb-sync` element appears in the README but is not present in the polymer.elements catalog.

Trying to sync a local pouch with a working coucdb doesn't work. No errors are shown but no replication happens.

### Expected outcome

`app-pouchdb-sync` element appears in the polymer.elements catalog and is properly documented.

It correctly syncs two databases.

### Actual outcome

Nothing happens when I add `app-pouchdb-sync` to a polymer project.

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by learningstacks** [comment]
As far as I can determine Polymer is prefixing the database name passed in src attribute with the web addess the app is being served from. In my case for example I use 

```
<app-pouchdb-sync 
            src="timecards"
            target="http://localhost:5984/timecards"
            bidirectional
            log>
</app-pouchdb-sync>
```
No sync occurs. In the dev tools I see the value of src actually used is http://localhost:8081/src/timecards. in the following code.
```
__computeSync: function(src, target, bidirectional) {
        var options = {
          live: true,
          retry: true
        }
        return bidirectional ?
          PouchDB.sync(src, target, options) :
          PouchDB.replicate(src, target, options);
      },
```

 The http://localhost:8081 is where Polymer serve is serving my app. At a breakppoint at the return statement I hacked the src variable back to just 'timecards' and it works.

I am guessing that src, like href, is treated specially by either the browser or Polymer. I suggest the property be renamed to source to avoid this issue.
